saga:
  flow:
    next-flow: order-create-topic
    end-flow: flow-end-topic
    sequence: order-create-topic,payment-create-topic,inventory-create-topic,flow-end-topic
#    Em caso de erro, so pode ser executado no fim do fluxo ou qdo nao tiver topic compensate
#    Todo fluxo deve chamar compensate carro ocorra erro.
#    Todo fluxo deve chamar compensate carro ocorra erro.
  order:
    create: order-create-topic
    next-flow: payment-create-topic
    compensate: 
    simulate-error: true
    finalize-flow: flow-end-topic
  payment:
    create: payment-create-topic
    next-flow: flow-end-topic
    compensate: order-compensate-topic
    simulate-error: false
    finalize-flow: 
  # inventory:
  #   create: inventory-create-topic
  #   next-flow: flow-end-topic
  #   compensate: payment-compensate-topic
  #   simulate-error: false
  #   finalize-flow: flow-end-topic
    